// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Only used by `prisma migrate diff --from-migrations` (scripts/
    // check-schema-drift.mjs), which replays the migrations directory into a
    // throwaway database. Prisma DROPS AND RECREATES whatever this points at,
    // so it must never be a real database — CI supplies a disposable postgres
    // service container. Undefined everywhere else, which is correct: no other
    // command needs it.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
