// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// No `import "dotenv/config"` here. dotenv is a devDependency, and Render
// installs with NODE_ENV=production, which makes npm skip devDependencies —
// so the import fails there with "Cannot find module" and takes the whole
// deploy down as soon as the build runs `prisma migrate deploy`.
//
// It was doing nothing anyway: dotenv reads `.env`, and this project keeps
// its local config in `.env.local`, which dotenv does not load. Render
// supplies environment variables directly, and local Prisma commands take
// DATABASE_URL from the environment.
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Only used by `prisma migrate diff --from-migrations` (scripts/
    // check-schema-drift.mjs), which replays the migrations directory into a
    // throwaway database. Prisma DROPS AND RECREATES whatever this points at,
    // so it must never be a real database — CI supplies a disposable postgres
    // service container. Undefined everywhere else, which is correct: no other
    // command needs it.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
